class TranslationEn {
  static Map<String, String> translation = {
    'K_TITLE': 'TCHOMBE',
    'K_SPLASHSCREENFIRSTTEXT':
        'No more headache of choosing your clothes every morning',
    'K_SPLASHSCREENSECONDTEXT': 'Choose your outfit of the day',
    'K_SPLASHSCREENTHIRDTEXT': 'Plan your looks for the week',
    'K_START': 'Start',
    'K_NEXT': 'Next',
    'K_HOME': 'Home',
    'K_PLANNING': 'Planning',
    'K_GENERALLOOK': 'Looks',
    'K_CLOTHES': 'Ware robe',
    'K_DETAILCLOTHES': 'Clothing detail',
    'K_LOOK_DETAIL': 'Look detail',
    'K_TYPE': 'Type',
    'K_BRAND': 'Brand',
    'K_COLOR': 'Color',
    'K_PRICE': 'Price',
    'K_DEVICE': "\$",
    'K_ADD_CLOTHES': 'Add Clothing',
    'K_CHANGELOCALELANGUAGE': 'Choose your locale language',
    'K_LANGUAGE': 'Language',
    'K_ERROR': 'Error',
    'K_NO_IMAGE_PICKER': 'No image picked',
    'K_IMAGE': 'Image',
    'K_IMAGE_SOURCE': 'Select image source',
    'K_CAMERA': 'Camera',
    'K_GALERY': 'Galery',
    'K_SELECT_TYPE': 'Select type',
    'K_RESET': 'Reset',
    'K_SAVE': 'Save',
    'K_EDIT_CLOTHES': 'Edit Clothes',
    'K_ALL': 'All',
    'K_TOP': 'High',
    'K_JEWELRY': 'Jewelry',
    'K_BAG': 'Bag',
    'K_BOTTOM': 'Bottom',
    'K_SHOES': 'Shoes',
    'K_ACCESSORY': 'Accessory',
    'K_OTHER': 'Other',
    'K_ITEMS_SELECTED': 'Select',
    'K_EVENING': 'Evening',
    'K_MARIAGE': 'Wedding',
    'K_OUTSIDE': 'Outdoor',
    'K_CLASS': 'Class',
    'K_WORK': 'Work',
    'K_HOUSE': 'Home',
    'K_HOLLY_DAY': 'Party',
    'K_SUCCES': 'Success',
    'K_CREATE_SUCCEFULL': 'Successfully Created',
    'K_EDIT_SUCCEFULL': 'Successfully modified',
    'K_DELETE_SUCCEFULL': 'Successfully deleted',
    'K_FILL_ALL_FIELD': 'Please fill in all fields',
    'K_EDIT_LOOK': 'Edit look',
    'K_ADD_LOOK': 'Add Look',
    'K_DESCRIPTION': 'Description',
    'K_CLOTHES_NAME': 'Clothes name',
    'K_SELECT_CATEGORIES': 'Categories',
    'K_LOOK_COST': 'Cost',
    'K_CREATE': 'Create',
    'K_CANNOT_EMPTY': 'This field cannot be empty',
    'K_MESSAGE_DILOG_TOTAL_COST_CLOTHES':
        'The total amount of your wardrobe is',
    'K_DELETE_MESSAGE': 'Do you really want to delete?',
    'K_CONFIRM': 'Confirm',
    'K_DELETE': 'Delete',
    'K_EDIT': 'Edit',
    'K_CANCEL': 'Cancel',
    'K_Ok': 'Ok',
    'K_COST': 'Cost',
    'K_CAN_BE_NUMERIC': 'Ivalid field',
    'K_SHARE': 'Share',
    'K_CHANGE': 'Change',
    'K_PLAN_LOOK': 'Plan look',
    'K_CHOOSE_LOOK': 'Choose look',
    'K_CHOOSE_DATE': 'Choose a date',
    'K_LOOK_OF_THE_DAY': 'Look of day',
    'K_NOT_LOOK_OF_THE_DAY': 'Not look plan',
    'K_PLAN': 'Plan'
  };
}
