class TranslationFr {
  static Map<String, String> translation = {
    'K_TITLE': 'TCHOMBE',
    'K_SPLASHSCREENFIRSTTEXT':
        'Finis le casse tête du choix de vos vêtements chaque matin',
    'K_SPLASHSCREENSECONDTEXT': 'Choisis ton vêtement du jour',
    'K_SPLASHSCREENTHIRDTEXT': 'Planifiez vos looks de la semaine',
    'K_START': 'Commencer',
    'K_NEXT': 'Suivant',
    'K_HOME': 'Accueil',
    'K_PLANNING': 'Planification',
    'K_GENERALLOOK': 'Looks',
    'K_CLOTHES': 'Garde robe',
    'K_DETAILCLOTHES': 'Détail vêtement',
    'K_LOOK_DETAIL': ' Détail look',
    'K_TYPE': 'Type',
    'K_BRAND': 'Marque',
    'K_COLOR': 'Couleur',
    'K_PRICE': 'Prix',
    'K_DEVICE': 'FCFA',
    'K_ADD_CLOTHES': 'Ajouter de Vêtement',
    'K_CHANGELOCALELANGUAGE': 'Choisissez votre langue locale',
    'K_LANGUAGE': 'Langage',
    'K_ERROR': 'Erreur',
    'K_NO_IMAGE_PICKER': 'Pas d\'image selectionner',
    'K_IMAGE': 'Image',
    'K_IMAGE_SOURCE': 'Selectionnez la source de image',
    'K_CAMERA': 'Camera',
    'K_GALERY': 'Galerie',
    'K_SELECT_TYPE': 'Selectionnez le type',
    'K_RESET': 'Effacer',
    'K_SAVE': 'Enregistrer',
    'K_EDIT_CLOTHES': 'Editer un Vêtement',
    'K_ALL': 'Tous',
    'K_TOP': 'Haut',
    'K_JEWELRY': 'Bijoux',
    'K_BAG': 'Sac',
    'K_BOTTOM': 'Bas',
    'K_SHOES': 'Chaussures',
    'K_ACCESSORY': 'Accessoires',
    'K_OTHER': 'Autres',
    'K_ITEMS_SELECTED': 'Coché',
    'K_EVENING': 'Soirée',
    'K_MARIAGE': 'Mariage',
    'K_OUTSIDE': 'Sortie',
    'K_CLASS': 'Classe',
    'K_HOUSE': 'Maison',
    'K_WORK': 'Travail',
    'K_HOLLY_DAY': 'Fête',
    'K_SUCCES': 'Succès',
    'K_CREATE_SUCCEFULL': 'Enregistré avec succès',
    'K_EDIT_SUCCEFULL': 'Modifier avec succès',
    'K_DELETE_SUCCEFULL': 'Supprimer avec succès',
    'K_FILL_ALL_FIELD': 'Bien vouloir remplir tous les champs',
    'K_EDIT_LOOK': 'Modiffier look',
    'K_ADD_LOOK': 'Ajoutter un Look',
    'K_DESCRIPTION': 'Description',
    'K_CLOTHES_NAME': 'Nom du vêtement',
    'K_SELECT_CATEGORIES': 'Catégories',
    'K_LOOK_COST': 'Coût',
    'K_CREATE': 'Créer',
    'K_CANNOT_EMPTY': 'Ce champ ne peut être vide',
    'K_MESSAGE_DILOG_TOTAL_COST_CLOTHES':
        'le montant total de votre garde robe s\'élève à',
    'K_DELETE_MESSAGE': 'Voulez-vous vraiment supprimer ?',
    'K_CONFIRM': 'Confirmation',
    'K_DELETE': 'Supprimer',
    'K_EDIT': 'Modifier',
    'K_CANCEL': 'Annuler',
    'K_Ok': 'Ok',
    'K_COST': 'Coût',
    'K_CAN_BE_NUMERIC': 'Champ invalide',
    'K_SHARE': 'Partager',
    'K_PLAN_LOOK': 'Planifier un look',
    'K_CHOOSE_LOOK': 'Choisir un look',
    'K_CHANGE': 'Changer',
    'K_CHOOSE_DATE': 'Choisir une date',
    'K_LOOK_OF_THE_DAY': 'Look du jour',
    'K_NOT_LOOK_OF_THE_DAY': 'Aucun look planifié',
    'K_PLAN': 'Planifier'
  };
}
